
# Name of workflow to be displyed on Github Console
name: PR Checks Workflow

# Triggers the workflow on separate events 
on:
  push:
    # Trigger the worflow on push event for all branches
    branches:
      -  '**'  
  pull_request:
    # Trigger the worflow on pull request event for main branch
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # "build" workflow
  build:

    name: Build and Test Go Application
    #The type of runner on which job will run
    runs-on: ubuntu-latest

    # steps can run commands, setup tasks or run an action
    steps: 
      - name: Checkout Source Code
        # action/checkout@v2 checks-out your repo under github workspace.
        uses: actions/checkout@v2

      # Run build on the code
      - name: Build
        env: 
          GOPROXY: "https://proxy.golang.org"
        # run runs command-line programs using the operating system's shell.
        run: exit 0

      # Run test cases on the code
      - name: Test Cases
        run: exit 0

      # Run gofmt on the code
      - name: Check Formatting using go fmt
        run: exit 0

      # Run go lint on the code
      - name: Run go lint 
        run: exit 0
